// source: Common/Common.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.Common.CommonNoti', null, global);
goog.exportSymbol('proto.Common.CommonNotifyOpcode', null, global);
goog.exportSymbol('proto.Common.CommonResponse', null, global);
goog.exportSymbol('proto.Common.ERROR', null, global);
goog.exportSymbol('proto.Common.Motify', null, global);
goog.exportSymbol('proto.Common.Status', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Common.CommonResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Common.CommonResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Common.CommonResponse.displayName = 'proto.Common.CommonResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Common.CommonNoti = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Common.CommonNoti, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Common.CommonNoti.displayName = 'proto.Common.CommonNoti';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Common.CommonResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.Common.CommonResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Common.CommonResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Common.CommonResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    nret: jspb.Message.getFieldWithDefault(msg, 1, 0),
    strmsg: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Common.CommonResponse}
 */
proto.Common.CommonResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Common.CommonResponse;
  return proto.Common.CommonResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Common.CommonResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Common.CommonResponse}
 */
proto.Common.CommonResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.Common.ERROR} */ (reader.readEnum());
      msg.setNret(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setStrmsg(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Common.CommonResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Common.CommonResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Common.CommonResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Common.CommonResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNret();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getStrmsg();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional ERROR nRet = 1;
 * @return {!proto.Common.ERROR}
 */
proto.Common.CommonResponse.prototype.getNret = function() {
  return /** @type {!proto.Common.ERROR} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.Common.ERROR} value
 * @return {!proto.Common.CommonResponse} returns this
 */
proto.Common.CommonResponse.prototype.setNret = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional string strMsg = 2;
 * @return {string}
 */
proto.Common.CommonResponse.prototype.getStrmsg = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.Common.CommonResponse} returns this
 */
proto.Common.CommonResponse.prototype.setStrmsg = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Common.CommonNoti.prototype.toObject = function(opt_includeInstance) {
  return proto.Common.CommonNoti.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Common.CommonNoti} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Common.CommonNoti.toObject = function(includeInstance, msg) {
  var f, obj = {
    strdata: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Common.CommonNoti}
 */
proto.Common.CommonNoti.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Common.CommonNoti;
  return proto.Common.CommonNoti.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Common.CommonNoti} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Common.CommonNoti}
 */
proto.Common.CommonNoti.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setStrdata(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Common.CommonNoti.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Common.CommonNoti.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Common.CommonNoti} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Common.CommonNoti.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStrdata();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string strData = 1;
 * @return {string}
 */
proto.Common.CommonNoti.prototype.getStrdata = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.Common.CommonNoti} returns this
 */
proto.Common.CommonNoti.prototype.setStrdata = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * @enum {number}
 */
proto.Common.Motify = {
  QUERYS: 0,
  CREATE: 1,
  DELETE: 2,
  CHANGE: 4
};

/**
 * @enum {number}
 */
proto.Common.Status = {
  QUERY: 0,
  JOIN: 1,
  EXIT: 2,
  WAIT: 4,
  FAIL: 8,
  VERIFY: 16,
  REJECT: 32,
  CANCEL: 64,
  OVER: 128
};

/**
 * @enum {number}
 */
proto.Common.ERROR = {
  SUCCESS: 0,
  E_FAIL: -1,
  E_TABLE_NOT_EXISTS: -2,
  E_GAME_PLAYING: -11,
  E_ALLOCATE_NO_TABLE: -100,
  E_PLAYER_NO_PLAYING_TABLE: -101,
  E_PLAYER_IN_CANCEL: -102,
  E_GATE_KICK_SERVER_CLOSED: -200,
  E_GATE_KICK_DUPLICATE_LOGIN: -201,
  E_ANTI_ADDICTION_NO_REALNAME: -202,
  E_ANTI_ADDICTION_NOT_PLAY_TIME: -203,
  E_GATE_KICK_BANNED: -204,
  E_MM_ALREADY_HAVE_TICKET: -1000,
  E_MM_HAS_TABLE_TO_PLAY: -1001,
  E_MM_STILL_MATCHING: -1002,
  E_MM_TICKET_NOT_EXIST: -1003,
  E_MM_GAME_MONEY_OUT_OF_RANGE: -1004,
  E_MM_PLAYER_OVER: -1101,
  E_MM_PLAYER_EMPTY: -1102,
  E_MM_ALREADY_START: -1103,
  E_MM_NUMS_FULL: -1104,
  E_CY_LOCK_FAILED: -2000,
  E_CY_NOT_LOCKED: -2001,
  E_CY_LOCKED: -2002,
  E_CY_NOT_ENOUGH: -2003,
  E_TASK_NOT_EXISTS: -3000,
  E_TASK_ALREADY_ACCEPTED: -3001,
  E_AWARD_NOT_EXISTS: -4000,
  E_RELIEVE_TOO_MUCH_MONEY: -5000,
  E_RELIEVE_NOT_ENOUGH_TIMES: -5001,
  E_SIGNIN_HAS_SIGNINED_TODAY: -6001,
  E_SIGNIN_NOT_SIGNINED_TODAY: -6002,
  E_SIGNIN_CANT_PRESIGNIN_ON_SUNDAY: -6003,
  E_SIGNIN_ALREADY_PRESIGNINED: -6004,
  E_RANKING_GIFT_NOT_ENOUGH_SCORE: -7000,
  E_RANKING_GIFT_STILL_COOLDOWN: -7001,
  E_SHAKE_NOT_ENOUGH_SHAKE_TIMES: -9001,
  E_LOGIN_AWARD_NOT_EXIST_IN_CONFIG: -10001,
  E_LOGIN_AWARD_HAS_APPLYED: -10002,
  E_VIP_AWARD_HAS_BEEN_RECEIVED: -11001,
  E_VIP_LEVEL_NOT_ENOUGH: -11002,
  E_VIP_NO_DAILY_AWARD_FOR_CURRENT_LEVEL: -11003,
  E_VIP_BET_NOT_ENOUGH: -11004,
  E_TUTORIAL_ALREADY_COMPLETED: -12001,
  E_REDEEM_CODE_NOT_EXISTS: -12100,
  E_REDEEM_CODE_ALREADY_REDEEMED: -12101,
  E_REDEEM_CODE_ALREADY_USED: -12102,
  E_REDEEM_CODE_WRONG_SOURCE: -12103,
  E_REDEEM_CODE_ALREADY_TYPE: -12104,
  E_REDEEM_CODE_LIMIT_TYPE: -12105,
  E_INVITE_NO_ID_CARD: -12200,
  E_INVITE_NOT_ENOUGH_LEVEL: -12201,
  E_INVITE_WRONG_CODE: -12202,
  E_INVITE_ALREADY_HAVE_INVITER: -12203,
  E_INVITE_CAN_NOT_INVITE_SELF: -12204,
  E_AD_REWARD_TIMES_LIMITED: -12300,
  E_REBATE_NONE_AWARD: -12401,
  E_EXCHANGE_LIMIT: -12501,
  E_EXCHANGE_PAY: -12502,
  E_EXCHANGE_UNMOTIFY: -12503,
  E_EXCHANGE_LESS: -12504,
  E_EXCHANGE_RENAME: -12505,
  E_EXCHANGE_BETLESS: -12506,
  E_EXCHANGE_TIMES: -12507
};

/**
 * @enum {number}
 */
proto.Common.CommonNotifyOpcode = {
  NOTIFY_UNKNOWN: 0,
  KICKOUT_NOTI: 1,
  LOGIN_NOTI: 2,
  IM_LOGIN_NOTI: 888,
  MM_MATCH_INFO_NOTI: 1000,
  MM_MATCH_RESULT_NOTI: 1001,
  MM_MATCH_OVER_NOTI: 1002,
  MM_MATCH_USER_NOTI: 1101,
  MM_MATCH_END_NOTI: 1102,
  MATCH_INFO_NOTI: 1200,
  MATCH_RESULT_NOTI: 1201,
  MATCH_OVER_NOTI: 1202,
  MATCH_USER_NOTI: 1203,
  MATCH_END_NOTI: 1204,
  CY_CURRENCY_CHANGE_NOTI: 2001,
  TASK_UPDATE_NOTI: 3000,
  TASK_COMPLETE_NOTI: 3001,
  RELIEVE_INFO_NOTI: 5001,
  SIGNIN_INFO_NOTI: 6001,
  MAIL_INFO_NOTI: 7001,
  ACHV_REPLACE_NOTI: 8001,
  CHARGE_GIFT_NOTI: 9001,
  SHAKE_SHAKE_NOTI: 10001,
  SOLICIT_WEALTH_NOTI: 11001,
  PAY_CHANGE_NOTI: 12001,
  ITEM_CHANGE_NOTI: 12002,
  PRIVILEGE_PAY_NOTI: 13001,
  PRIVILEGE_CARDS_INFO_NOTI: 13002,
  PRIVILEGE_WEEKLY_CARD_INFO_NOTI: 13003,
  PRIVILEGE_MONTHLY_CARD_INFO_NOTI: 13004,
  STORE_ORDER_COMPLETE: 14001,
  AWARD_INFO_NOTI: 15001,
  BULLETIN_NOTI: 16001,
  ROULETTE_INFO_NOTI: 17001,
  LOGIN_AWARD_INGO_NOTI: 18001,
  ITEM_USE_INFO_NOTI: 19001,
  DAILY_TASK_ACTIVITY_CONFIG_NOTI: 20001,
  VIP_INFO_NOTI: 20002,
  LUCKY_GIFT_INFO_NOTI: 20100,
  RANKING_NEW_SEASON_NOTI: 20200,
  TUTORIAL_STATUS_NOTI: 20300,
  TOURNAMENT_TABLE_NOTI: 20301,
  DAILY_FIRST_PATTERN_NOTI: 20400,
  DAILY_FIRST_PLAYER_NOTI: 20401,
  AD_REWARD_PLAYER_INFO: 20410,
  THIRD_LIST_REFRESH_NOTI: 20501,
  THIRD_ENTER_ACK_NOTI: 20502
};

goog.object.extend(exports, proto.Common);
