// source: GSMgr/GSMgr.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var Common_Common_pb = require('../Common/Common_pb.js');
goog.object.extend(proto, Common_Common_pb);
goog.exportSymbol('proto.GSMgr.AllocateTableAck', null, global);
goog.exportSymbol('proto.GSMgr.AllocateTableReq', null, global);
goog.exportSymbol('proto.GSMgr.DismissTableAck', null, global);
goog.exportSymbol('proto.GSMgr.DismissTableReq', null, global);
goog.exportSymbol('proto.GSMgr.KickPlyAck', null, global);
goog.exportSymbol('proto.GSMgr.KickPlyGet', null, global);
goog.exportSymbol('proto.GSMgr.RegisterGSAck', null, global);
goog.exportSymbol('proto.GSMgr.RegisterGSReq', null, global);
goog.exportSymbol('proto.GSMgr.ServerInfo', null, global);
goog.exportSymbol('proto.GSMgr.TableInfo', null, global);
goog.exportSymbol('proto.GSMgr.TableInfoReq', null, global);
goog.exportSymbol('proto.GSMgr.TableNumNoti', null, global);
goog.exportSymbol('proto.GSMgr.TableNumReq', null, global);
goog.exportSymbol('proto.GSMgr.TableOverAck', null, global);
goog.exportSymbol('proto.GSMgr.TableOverReq', null, global);
goog.exportSymbol('proto.GSMgr.TableStatus', null, global);
goog.exportSymbol('proto.GSMgr.TableStatusChangeNoti', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.GSMgr.AllocateTableReq = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.GSMgr.AllocateTableReq.repeatedFields_, null);
};
goog.inherits(proto.GSMgr.AllocateTableReq, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.GSMgr.AllocateTableReq.displayName = 'proto.GSMgr.AllocateTableReq';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.GSMgr.ServerInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.GSMgr.ServerInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.GSMgr.ServerInfo.displayName = 'proto.GSMgr.ServerInfo';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.GSMgr.TableInfoReq = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.GSMgr.TableInfoReq, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.GSMgr.TableInfoReq.displayName = 'proto.GSMgr.TableInfoReq';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.GSMgr.TableInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.GSMgr.TableInfo.repeatedFields_, null);
};
goog.inherits(proto.GSMgr.TableInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.GSMgr.TableInfo.displayName = 'proto.GSMgr.TableInfo';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.GSMgr.AllocateTableAck = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.GSMgr.AllocateTableAck, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.GSMgr.AllocateTableAck.displayName = 'proto.GSMgr.AllocateTableAck';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.GSMgr.RegisterGSReq = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.GSMgr.RegisterGSReq, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.GSMgr.RegisterGSReq.displayName = 'proto.GSMgr.RegisterGSReq';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.GSMgr.RegisterGSAck = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.GSMgr.RegisterGSAck, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.GSMgr.RegisterGSAck.displayName = 'proto.GSMgr.RegisterGSAck';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.GSMgr.TableOverReq = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.GSMgr.TableOverReq, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.GSMgr.TableOverReq.displayName = 'proto.GSMgr.TableOverReq';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.GSMgr.TableOverAck = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.GSMgr.TableOverAck, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.GSMgr.TableOverAck.displayName = 'proto.GSMgr.TableOverAck';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.GSMgr.TableStatusChangeNoti = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.GSMgr.TableStatusChangeNoti, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.GSMgr.TableStatusChangeNoti.displayName = 'proto.GSMgr.TableStatusChangeNoti';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.GSMgr.DismissTableReq = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.GSMgr.DismissTableReq, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.GSMgr.DismissTableReq.displayName = 'proto.GSMgr.DismissTableReq';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.GSMgr.DismissTableAck = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.GSMgr.DismissTableAck, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.GSMgr.DismissTableAck.displayName = 'proto.GSMgr.DismissTableAck';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.GSMgr.TableNumReq = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.GSMgr.TableNumReq, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.GSMgr.TableNumReq.displayName = 'proto.GSMgr.TableNumReq';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.GSMgr.TableNumNoti = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.GSMgr.TableNumNoti, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.GSMgr.TableNumNoti.displayName = 'proto.GSMgr.TableNumNoti';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.GSMgr.KickPlyGet = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.GSMgr.KickPlyGet, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.GSMgr.KickPlyGet.displayName = 'proto.GSMgr.KickPlyGet';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.GSMgr.KickPlyAck = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.GSMgr.KickPlyAck, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.GSMgr.KickPlyAck.displayName = 'proto.GSMgr.KickPlyAck';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.GSMgr.AllocateTableReq.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.GSMgr.AllocateTableReq.prototype.toObject = function(opt_includeInstance) {
  return proto.GSMgr.AllocateTableReq.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.GSMgr.AllocateTableReq} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GSMgr.AllocateTableReq.toObject = function(includeInstance, msg) {
  var f, obj = {
    ngameid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    arrplayersList: (f = jspb.Message.getRepeatedField(msg, 2)) == null ? undefined : f,
    strrule: jspb.Message.getFieldWithDefault(msg, 3, ""),
    strextra: jspb.Message.getFieldWithDefault(msg, 4, ""),
    mapplayerextraMap: (f = msg.getMapplayerextraMap()) ? f.toObject(includeInstance, undefined) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.GSMgr.AllocateTableReq}
 */
proto.GSMgr.AllocateTableReq.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.GSMgr.AllocateTableReq;
  return proto.GSMgr.AllocateTableReq.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.GSMgr.AllocateTableReq} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.GSMgr.AllocateTableReq}
 */
proto.GSMgr.AllocateTableReq.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setNgameid(value);
      break;
    case 2:
      var value = /** @type {!Array<number>} */ (reader.readPackedUint32());
      msg.setArrplayersList(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setStrrule(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setStrextra(value);
      break;
    case 5:
      var value = msg.getMapplayerextraMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readUint32, jspb.BinaryReader.prototype.readString, null, 0, "");
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.GSMgr.AllocateTableReq.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.GSMgr.AllocateTableReq.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.GSMgr.AllocateTableReq} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GSMgr.AllocateTableReq.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNgameid();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getArrplayersList();
  if (f.length > 0) {
    writer.writePackedUint32(
      2,
      f
    );
  }
  f = message.getStrrule();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getStrextra();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getMapplayerextraMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(5, writer, jspb.BinaryWriter.prototype.writeUint32, jspb.BinaryWriter.prototype.writeString);
  }
};


/**
 * optional uint32 nGameID = 1;
 * @return {number}
 */
proto.GSMgr.AllocateTableReq.prototype.getNgameid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.GSMgr.AllocateTableReq} returns this
 */
proto.GSMgr.AllocateTableReq.prototype.setNgameid = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * repeated uint32 arrPlayers = 2;
 * @return {!Array<number>}
 */
proto.GSMgr.AllocateTableReq.prototype.getArrplayersList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 2));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.GSMgr.AllocateTableReq} returns this
 */
proto.GSMgr.AllocateTableReq.prototype.setArrplayersList = function(value) {
  return jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.GSMgr.AllocateTableReq} returns this
 */
proto.GSMgr.AllocateTableReq.prototype.addArrplayers = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.GSMgr.AllocateTableReq} returns this
 */
proto.GSMgr.AllocateTableReq.prototype.clearArrplayersList = function() {
  return this.setArrplayersList([]);
};


/**
 * optional string strRule = 3;
 * @return {string}
 */
proto.GSMgr.AllocateTableReq.prototype.getStrrule = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.GSMgr.AllocateTableReq} returns this
 */
proto.GSMgr.AllocateTableReq.prototype.setStrrule = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string strExtra = 4;
 * @return {string}
 */
proto.GSMgr.AllocateTableReq.prototype.getStrextra = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.GSMgr.AllocateTableReq} returns this
 */
proto.GSMgr.AllocateTableReq.prototype.setStrextra = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * map<uint32, string> mapPlayerExtra = 5;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<number,string>}
 */
proto.GSMgr.AllocateTableReq.prototype.getMapplayerextraMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<number,string>} */ (
      jspb.Message.getMapField(this, 5, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.GSMgr.AllocateTableReq} returns this
 */
proto.GSMgr.AllocateTableReq.prototype.clearMapplayerextraMap = function() {
  this.getMapplayerextraMap().clear();
  return this;};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.GSMgr.ServerInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.GSMgr.ServerInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.GSMgr.ServerInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GSMgr.ServerInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    ngameid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    strservername: jspb.Message.getFieldWithDefault(msg, 2, ""),
    strserverid: jspb.Message.getFieldWithDefault(msg, 3, ""),
    straddr: jspb.Message.getFieldWithDefault(msg, 4, ""),
    nmaxtable: jspb.Message.getFieldWithDefault(msg, 5, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.GSMgr.ServerInfo}
 */
proto.GSMgr.ServerInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.GSMgr.ServerInfo;
  return proto.GSMgr.ServerInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.GSMgr.ServerInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.GSMgr.ServerInfo}
 */
proto.GSMgr.ServerInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setNgameid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setStrservername(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setStrserverid(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setStraddr(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setNmaxtable(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.GSMgr.ServerInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.GSMgr.ServerInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.GSMgr.ServerInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GSMgr.ServerInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNgameid();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getStrservername();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getStrserverid();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getStraddr();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getNmaxtable();
  if (f !== 0) {
    writer.writeUint32(
      5,
      f
    );
  }
};


/**
 * optional uint32 nGameID = 1;
 * @return {number}
 */
proto.GSMgr.ServerInfo.prototype.getNgameid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.GSMgr.ServerInfo} returns this
 */
proto.GSMgr.ServerInfo.prototype.setNgameid = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string strServerName = 2;
 * @return {string}
 */
proto.GSMgr.ServerInfo.prototype.getStrservername = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.GSMgr.ServerInfo} returns this
 */
proto.GSMgr.ServerInfo.prototype.setStrservername = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string strServerID = 3;
 * @return {string}
 */
proto.GSMgr.ServerInfo.prototype.getStrserverid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.GSMgr.ServerInfo} returns this
 */
proto.GSMgr.ServerInfo.prototype.setStrserverid = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string strAddr = 4;
 * @return {string}
 */
proto.GSMgr.ServerInfo.prototype.getStraddr = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.GSMgr.ServerInfo} returns this
 */
proto.GSMgr.ServerInfo.prototype.setStraddr = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional uint32 nMaxTable = 5;
 * @return {number}
 */
proto.GSMgr.ServerInfo.prototype.getNmaxtable = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.GSMgr.ServerInfo} returns this
 */
proto.GSMgr.ServerInfo.prototype.setNmaxtable = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.GSMgr.TableInfoReq.prototype.toObject = function(opt_includeInstance) {
  return proto.GSMgr.TableInfoReq.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.GSMgr.TableInfoReq} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GSMgr.TableInfoReq.toObject = function(includeInstance, msg) {
  var f, obj = {
    strtableid: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.GSMgr.TableInfoReq}
 */
proto.GSMgr.TableInfoReq.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.GSMgr.TableInfoReq;
  return proto.GSMgr.TableInfoReq.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.GSMgr.TableInfoReq} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.GSMgr.TableInfoReq}
 */
proto.GSMgr.TableInfoReq.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setStrtableid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.GSMgr.TableInfoReq.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.GSMgr.TableInfoReq.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.GSMgr.TableInfoReq} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GSMgr.TableInfoReq.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStrtableid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string strTableID = 1;
 * @return {string}
 */
proto.GSMgr.TableInfoReq.prototype.getStrtableid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.GSMgr.TableInfoReq} returns this
 */
proto.GSMgr.TableInfoReq.prototype.setStrtableid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.GSMgr.TableInfo.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.GSMgr.TableInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.GSMgr.TableInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.GSMgr.TableInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GSMgr.TableInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    strtableid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    arrplayersList: (f = jspb.Message.getRepeatedField(msg, 2)) == null ? undefined : f,
    stserverinfo: (f = msg.getStserverinfo()) && proto.GSMgr.ServerInfo.toObject(includeInstance, f),
    strrule: jspb.Message.getFieldWithDefault(msg, 4, ""),
    strextra: jspb.Message.getFieldWithDefault(msg, 5, ""),
    nstatus: jspb.Message.getFieldWithDefault(msg, 6, 0),
    mapplayerextraMap: (f = msg.getMapplayerextraMap()) ? f.toObject(includeInstance, undefined) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.GSMgr.TableInfo}
 */
proto.GSMgr.TableInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.GSMgr.TableInfo;
  return proto.GSMgr.TableInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.GSMgr.TableInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.GSMgr.TableInfo}
 */
proto.GSMgr.TableInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setStrtableid(value);
      break;
    case 2:
      var value = /** @type {!Array<number>} */ (reader.readPackedUint32());
      msg.setArrplayersList(value);
      break;
    case 3:
      var value = new proto.GSMgr.ServerInfo;
      reader.readMessage(value,proto.GSMgr.ServerInfo.deserializeBinaryFromReader);
      msg.setStserverinfo(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setStrrule(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setStrextra(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setNstatus(value);
      break;
    case 7:
      var value = msg.getMapplayerextraMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readUint32, jspb.BinaryReader.prototype.readString, null, 0, "");
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.GSMgr.TableInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.GSMgr.TableInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.GSMgr.TableInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GSMgr.TableInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStrtableid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getArrplayersList();
  if (f.length > 0) {
    writer.writePackedUint32(
      2,
      f
    );
  }
  f = message.getStserverinfo();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.GSMgr.ServerInfo.serializeBinaryToWriter
    );
  }
  f = message.getStrrule();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getStrextra();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getNstatus();
  if (f !== 0) {
    writer.writeInt32(
      6,
      f
    );
  }
  f = message.getMapplayerextraMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(7, writer, jspb.BinaryWriter.prototype.writeUint32, jspb.BinaryWriter.prototype.writeString);
  }
};


/**
 * optional string strTableID = 1;
 * @return {string}
 */
proto.GSMgr.TableInfo.prototype.getStrtableid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.GSMgr.TableInfo} returns this
 */
proto.GSMgr.TableInfo.prototype.setStrtableid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated uint32 arrPlayers = 2;
 * @return {!Array<number>}
 */
proto.GSMgr.TableInfo.prototype.getArrplayersList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 2));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.GSMgr.TableInfo} returns this
 */
proto.GSMgr.TableInfo.prototype.setArrplayersList = function(value) {
  return jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.GSMgr.TableInfo} returns this
 */
proto.GSMgr.TableInfo.prototype.addArrplayers = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.GSMgr.TableInfo} returns this
 */
proto.GSMgr.TableInfo.prototype.clearArrplayersList = function() {
  return this.setArrplayersList([]);
};


/**
 * optional ServerInfo stServerInfo = 3;
 * @return {?proto.GSMgr.ServerInfo}
 */
proto.GSMgr.TableInfo.prototype.getStserverinfo = function() {
  return /** @type{?proto.GSMgr.ServerInfo} */ (
    jspb.Message.getWrapperField(this, proto.GSMgr.ServerInfo, 3));
};


/**
 * @param {?proto.GSMgr.ServerInfo|undefined} value
 * @return {!proto.GSMgr.TableInfo} returns this
*/
proto.GSMgr.TableInfo.prototype.setStserverinfo = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.GSMgr.TableInfo} returns this
 */
proto.GSMgr.TableInfo.prototype.clearStserverinfo = function() {
  return this.setStserverinfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.GSMgr.TableInfo.prototype.hasStserverinfo = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional string strRule = 4;
 * @return {string}
 */
proto.GSMgr.TableInfo.prototype.getStrrule = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.GSMgr.TableInfo} returns this
 */
proto.GSMgr.TableInfo.prototype.setStrrule = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string strExtra = 5;
 * @return {string}
 */
proto.GSMgr.TableInfo.prototype.getStrextra = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.GSMgr.TableInfo} returns this
 */
proto.GSMgr.TableInfo.prototype.setStrextra = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional int32 nStatus = 6;
 * @return {number}
 */
proto.GSMgr.TableInfo.prototype.getNstatus = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.GSMgr.TableInfo} returns this
 */
proto.GSMgr.TableInfo.prototype.setNstatus = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * map<uint32, string> mapPlayerExtra = 7;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<number,string>}
 */
proto.GSMgr.TableInfo.prototype.getMapplayerextraMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<number,string>} */ (
      jspb.Message.getMapField(this, 7, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.GSMgr.TableInfo} returns this
 */
proto.GSMgr.TableInfo.prototype.clearMapplayerextraMap = function() {
  this.getMapplayerextraMap().clear();
  return this;};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.GSMgr.AllocateTableAck.prototype.toObject = function(opt_includeInstance) {
  return proto.GSMgr.AllocateTableAck.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.GSMgr.AllocateTableAck} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GSMgr.AllocateTableAck.toObject = function(includeInstance, msg) {
  var f, obj = {
    nret: jspb.Message.getFieldWithDefault(msg, 1, 0),
    sttable: (f = msg.getSttable()) && proto.GSMgr.TableInfo.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.GSMgr.AllocateTableAck}
 */
proto.GSMgr.AllocateTableAck.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.GSMgr.AllocateTableAck;
  return proto.GSMgr.AllocateTableAck.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.GSMgr.AllocateTableAck} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.GSMgr.AllocateTableAck}
 */
proto.GSMgr.AllocateTableAck.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.Common.ERROR} */ (reader.readEnum());
      msg.setNret(value);
      break;
    case 2:
      var value = new proto.GSMgr.TableInfo;
      reader.readMessage(value,proto.GSMgr.TableInfo.deserializeBinaryFromReader);
      msg.setSttable(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.GSMgr.AllocateTableAck.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.GSMgr.AllocateTableAck.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.GSMgr.AllocateTableAck} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GSMgr.AllocateTableAck.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNret();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getSttable();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.GSMgr.TableInfo.serializeBinaryToWriter
    );
  }
};


/**
 * optional Common.ERROR nRet = 1;
 * @return {!proto.Common.ERROR}
 */
proto.GSMgr.AllocateTableAck.prototype.getNret = function() {
  return /** @type {!proto.Common.ERROR} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.Common.ERROR} value
 * @return {!proto.GSMgr.AllocateTableAck} returns this
 */
proto.GSMgr.AllocateTableAck.prototype.setNret = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional TableInfo stTable = 2;
 * @return {?proto.GSMgr.TableInfo}
 */
proto.GSMgr.AllocateTableAck.prototype.getSttable = function() {
  return /** @type{?proto.GSMgr.TableInfo} */ (
    jspb.Message.getWrapperField(this, proto.GSMgr.TableInfo, 2));
};


/**
 * @param {?proto.GSMgr.TableInfo|undefined} value
 * @return {!proto.GSMgr.AllocateTableAck} returns this
*/
proto.GSMgr.AllocateTableAck.prototype.setSttable = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.GSMgr.AllocateTableAck} returns this
 */
proto.GSMgr.AllocateTableAck.prototype.clearSttable = function() {
  return this.setSttable(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.GSMgr.AllocateTableAck.prototype.hasSttable = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.GSMgr.RegisterGSReq.prototype.toObject = function(opt_includeInstance) {
  return proto.GSMgr.RegisterGSReq.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.GSMgr.RegisterGSReq} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GSMgr.RegisterGSReq.toObject = function(includeInstance, msg) {
  var f, obj = {
    stserverinfo: (f = msg.getStserverinfo()) && proto.GSMgr.ServerInfo.toObject(includeInstance, f),
    breconnect: jspb.Message.getBooleanFieldWithDefault(msg, 2, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.GSMgr.RegisterGSReq}
 */
proto.GSMgr.RegisterGSReq.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.GSMgr.RegisterGSReq;
  return proto.GSMgr.RegisterGSReq.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.GSMgr.RegisterGSReq} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.GSMgr.RegisterGSReq}
 */
proto.GSMgr.RegisterGSReq.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.GSMgr.ServerInfo;
      reader.readMessage(value,proto.GSMgr.ServerInfo.deserializeBinaryFromReader);
      msg.setStserverinfo(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setBreconnect(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.GSMgr.RegisterGSReq.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.GSMgr.RegisterGSReq.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.GSMgr.RegisterGSReq} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GSMgr.RegisterGSReq.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStserverinfo();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.GSMgr.ServerInfo.serializeBinaryToWriter
    );
  }
  f = message.getBreconnect();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
};


/**
 * optional ServerInfo stServerInfo = 1;
 * @return {?proto.GSMgr.ServerInfo}
 */
proto.GSMgr.RegisterGSReq.prototype.getStserverinfo = function() {
  return /** @type{?proto.GSMgr.ServerInfo} */ (
    jspb.Message.getWrapperField(this, proto.GSMgr.ServerInfo, 1));
};


/**
 * @param {?proto.GSMgr.ServerInfo|undefined} value
 * @return {!proto.GSMgr.RegisterGSReq} returns this
*/
proto.GSMgr.RegisterGSReq.prototype.setStserverinfo = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.GSMgr.RegisterGSReq} returns this
 */
proto.GSMgr.RegisterGSReq.prototype.clearStserverinfo = function() {
  return this.setStserverinfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.GSMgr.RegisterGSReq.prototype.hasStserverinfo = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional bool bReconnect = 2;
 * @return {boolean}
 */
proto.GSMgr.RegisterGSReq.prototype.getBreconnect = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.GSMgr.RegisterGSReq} returns this
 */
proto.GSMgr.RegisterGSReq.prototype.setBreconnect = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.GSMgr.RegisterGSAck.prototype.toObject = function(opt_includeInstance) {
  return proto.GSMgr.RegisterGSAck.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.GSMgr.RegisterGSAck} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GSMgr.RegisterGSAck.toObject = function(includeInstance, msg) {
  var f, obj = {
    nret: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.GSMgr.RegisterGSAck}
 */
proto.GSMgr.RegisterGSAck.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.GSMgr.RegisterGSAck;
  return proto.GSMgr.RegisterGSAck.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.GSMgr.RegisterGSAck} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.GSMgr.RegisterGSAck}
 */
proto.GSMgr.RegisterGSAck.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.Common.ERROR} */ (reader.readEnum());
      msg.setNret(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.GSMgr.RegisterGSAck.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.GSMgr.RegisterGSAck.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.GSMgr.RegisterGSAck} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GSMgr.RegisterGSAck.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNret();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
};


/**
 * optional Common.ERROR nRet = 1;
 * @return {!proto.Common.ERROR}
 */
proto.GSMgr.RegisterGSAck.prototype.getNret = function() {
  return /** @type {!proto.Common.ERROR} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.Common.ERROR} value
 * @return {!proto.GSMgr.RegisterGSAck} returns this
 */
proto.GSMgr.RegisterGSAck.prototype.setNret = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.GSMgr.TableOverReq.prototype.toObject = function(opt_includeInstance) {
  return proto.GSMgr.TableOverReq.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.GSMgr.TableOverReq} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GSMgr.TableOverReq.toObject = function(includeInstance, msg) {
  var f, obj = {
    strtableid: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.GSMgr.TableOverReq}
 */
proto.GSMgr.TableOverReq.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.GSMgr.TableOverReq;
  return proto.GSMgr.TableOverReq.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.GSMgr.TableOverReq} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.GSMgr.TableOverReq}
 */
proto.GSMgr.TableOverReq.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setStrtableid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.GSMgr.TableOverReq.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.GSMgr.TableOverReq.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.GSMgr.TableOverReq} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GSMgr.TableOverReq.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStrtableid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string strTableID = 1;
 * @return {string}
 */
proto.GSMgr.TableOverReq.prototype.getStrtableid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.GSMgr.TableOverReq} returns this
 */
proto.GSMgr.TableOverReq.prototype.setStrtableid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.GSMgr.TableOverAck.prototype.toObject = function(opt_includeInstance) {
  return proto.GSMgr.TableOverAck.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.GSMgr.TableOverAck} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GSMgr.TableOverAck.toObject = function(includeInstance, msg) {
  var f, obj = {
    nret: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.GSMgr.TableOverAck}
 */
proto.GSMgr.TableOverAck.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.GSMgr.TableOverAck;
  return proto.GSMgr.TableOverAck.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.GSMgr.TableOverAck} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.GSMgr.TableOverAck}
 */
proto.GSMgr.TableOverAck.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.Common.ERROR} */ (reader.readEnum());
      msg.setNret(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.GSMgr.TableOverAck.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.GSMgr.TableOverAck.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.GSMgr.TableOverAck} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GSMgr.TableOverAck.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNret();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
};


/**
 * optional Common.ERROR nRet = 1;
 * @return {!proto.Common.ERROR}
 */
proto.GSMgr.TableOverAck.prototype.getNret = function() {
  return /** @type {!proto.Common.ERROR} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.Common.ERROR} value
 * @return {!proto.GSMgr.TableOverAck} returns this
 */
proto.GSMgr.TableOverAck.prototype.setNret = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.GSMgr.TableStatusChangeNoti.prototype.toObject = function(opt_includeInstance) {
  return proto.GSMgr.TableStatusChangeNoti.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.GSMgr.TableStatusChangeNoti} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GSMgr.TableStatusChangeNoti.toObject = function(includeInstance, msg) {
  var f, obj = {
    strtableid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    nstatus: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.GSMgr.TableStatusChangeNoti}
 */
proto.GSMgr.TableStatusChangeNoti.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.GSMgr.TableStatusChangeNoti;
  return proto.GSMgr.TableStatusChangeNoti.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.GSMgr.TableStatusChangeNoti} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.GSMgr.TableStatusChangeNoti}
 */
proto.GSMgr.TableStatusChangeNoti.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setStrtableid(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setNstatus(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.GSMgr.TableStatusChangeNoti.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.GSMgr.TableStatusChangeNoti.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.GSMgr.TableStatusChangeNoti} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GSMgr.TableStatusChangeNoti.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStrtableid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getNstatus();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
};


/**
 * optional string strTableID = 1;
 * @return {string}
 */
proto.GSMgr.TableStatusChangeNoti.prototype.getStrtableid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.GSMgr.TableStatusChangeNoti} returns this
 */
proto.GSMgr.TableStatusChangeNoti.prototype.setStrtableid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int32 nStatus = 2;
 * @return {number}
 */
proto.GSMgr.TableStatusChangeNoti.prototype.getNstatus = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.GSMgr.TableStatusChangeNoti} returns this
 */
proto.GSMgr.TableStatusChangeNoti.prototype.setNstatus = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.GSMgr.DismissTableReq.prototype.toObject = function(opt_includeInstance) {
  return proto.GSMgr.DismissTableReq.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.GSMgr.DismissTableReq} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GSMgr.DismissTableReq.toObject = function(includeInstance, msg) {
  var f, obj = {
    strtableid: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.GSMgr.DismissTableReq}
 */
proto.GSMgr.DismissTableReq.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.GSMgr.DismissTableReq;
  return proto.GSMgr.DismissTableReq.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.GSMgr.DismissTableReq} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.GSMgr.DismissTableReq}
 */
proto.GSMgr.DismissTableReq.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setStrtableid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.GSMgr.DismissTableReq.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.GSMgr.DismissTableReq.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.GSMgr.DismissTableReq} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GSMgr.DismissTableReq.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStrtableid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string strTableID = 1;
 * @return {string}
 */
proto.GSMgr.DismissTableReq.prototype.getStrtableid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.GSMgr.DismissTableReq} returns this
 */
proto.GSMgr.DismissTableReq.prototype.setStrtableid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.GSMgr.DismissTableAck.prototype.toObject = function(opt_includeInstance) {
  return proto.GSMgr.DismissTableAck.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.GSMgr.DismissTableAck} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GSMgr.DismissTableAck.toObject = function(includeInstance, msg) {
  var f, obj = {
    nret: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.GSMgr.DismissTableAck}
 */
proto.GSMgr.DismissTableAck.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.GSMgr.DismissTableAck;
  return proto.GSMgr.DismissTableAck.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.GSMgr.DismissTableAck} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.GSMgr.DismissTableAck}
 */
proto.GSMgr.DismissTableAck.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.Common.ERROR} */ (reader.readEnum());
      msg.setNret(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.GSMgr.DismissTableAck.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.GSMgr.DismissTableAck.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.GSMgr.DismissTableAck} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GSMgr.DismissTableAck.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNret();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
};


/**
 * optional Common.ERROR nRet = 1;
 * @return {!proto.Common.ERROR}
 */
proto.GSMgr.DismissTableAck.prototype.getNret = function() {
  return /** @type {!proto.Common.ERROR} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.Common.ERROR} value
 * @return {!proto.GSMgr.DismissTableAck} returns this
 */
proto.GSMgr.DismissTableAck.prototype.setNret = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.GSMgr.TableNumReq.prototype.toObject = function(opt_includeInstance) {
  return proto.GSMgr.TableNumReq.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.GSMgr.TableNumReq} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GSMgr.TableNumReq.toObject = function(includeInstance, msg) {
  var f, obj = {
    ngameid: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.GSMgr.TableNumReq}
 */
proto.GSMgr.TableNumReq.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.GSMgr.TableNumReq;
  return proto.GSMgr.TableNumReq.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.GSMgr.TableNumReq} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.GSMgr.TableNumReq}
 */
proto.GSMgr.TableNumReq.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setNgameid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.GSMgr.TableNumReq.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.GSMgr.TableNumReq.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.GSMgr.TableNumReq} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GSMgr.TableNumReq.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNgameid();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
};


/**
 * optional uint32 nGameID = 1;
 * @return {number}
 */
proto.GSMgr.TableNumReq.prototype.getNgameid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.GSMgr.TableNumReq} returns this
 */
proto.GSMgr.TableNumReq.prototype.setNgameid = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.GSMgr.TableNumNoti.prototype.toObject = function(opt_includeInstance) {
  return proto.GSMgr.TableNumNoti.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.GSMgr.TableNumNoti} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GSMgr.TableNumNoti.toObject = function(includeInstance, msg) {
  var f, obj = {
    ngameid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    ntable: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.GSMgr.TableNumNoti}
 */
proto.GSMgr.TableNumNoti.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.GSMgr.TableNumNoti;
  return proto.GSMgr.TableNumNoti.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.GSMgr.TableNumNoti} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.GSMgr.TableNumNoti}
 */
proto.GSMgr.TableNumNoti.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setNgameid(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setNtable(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.GSMgr.TableNumNoti.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.GSMgr.TableNumNoti.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.GSMgr.TableNumNoti} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GSMgr.TableNumNoti.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNgameid();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getNtable();
  if (f !== 0) {
    writer.writeUint32(
      2,
      f
    );
  }
};


/**
 * optional uint32 nGameID = 1;
 * @return {number}
 */
proto.GSMgr.TableNumNoti.prototype.getNgameid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.GSMgr.TableNumNoti} returns this
 */
proto.GSMgr.TableNumNoti.prototype.setNgameid = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional uint32 nTable = 2;
 * @return {number}
 */
proto.GSMgr.TableNumNoti.prototype.getNtable = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.GSMgr.TableNumNoti} returns this
 */
proto.GSMgr.TableNumNoti.prototype.setNtable = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.GSMgr.KickPlyGet.prototype.toObject = function(opt_includeInstance) {
  return proto.GSMgr.KickPlyGet.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.GSMgr.KickPlyGet} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GSMgr.KickPlyGet.toObject = function(includeInstance, msg) {
  var f, obj = {
    npid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    strtableid: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.GSMgr.KickPlyGet}
 */
proto.GSMgr.KickPlyGet.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.GSMgr.KickPlyGet;
  return proto.GSMgr.KickPlyGet.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.GSMgr.KickPlyGet} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.GSMgr.KickPlyGet}
 */
proto.GSMgr.KickPlyGet.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setNpid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setStrtableid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.GSMgr.KickPlyGet.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.GSMgr.KickPlyGet.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.GSMgr.KickPlyGet} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GSMgr.KickPlyGet.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNpid();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getStrtableid();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional uint32 nPID = 1;
 * @return {number}
 */
proto.GSMgr.KickPlyGet.prototype.getNpid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.GSMgr.KickPlyGet} returns this
 */
proto.GSMgr.KickPlyGet.prototype.setNpid = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string strTableID = 2;
 * @return {string}
 */
proto.GSMgr.KickPlyGet.prototype.getStrtableid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.GSMgr.KickPlyGet} returns this
 */
proto.GSMgr.KickPlyGet.prototype.setStrtableid = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.GSMgr.KickPlyAck.prototype.toObject = function(opt_includeInstance) {
  return proto.GSMgr.KickPlyAck.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.GSMgr.KickPlyAck} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GSMgr.KickPlyAck.toObject = function(includeInstance, msg) {
  var f, obj = {
    cret: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.GSMgr.KickPlyAck}
 */
proto.GSMgr.KickPlyAck.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.GSMgr.KickPlyAck;
  return proto.GSMgr.KickPlyAck.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.GSMgr.KickPlyAck} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.GSMgr.KickPlyAck}
 */
proto.GSMgr.KickPlyAck.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readSint32());
      msg.setCret(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.GSMgr.KickPlyAck.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.GSMgr.KickPlyAck.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.GSMgr.KickPlyAck} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GSMgr.KickPlyAck.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCret();
  if (f !== 0) {
    writer.writeSint32(
      1,
      f
    );
  }
};


/**
 * optional sint32 CRet = 1;
 * @return {number}
 */
proto.GSMgr.KickPlyAck.prototype.getCret = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.GSMgr.KickPlyAck} returns this
 */
proto.GSMgr.KickPlyAck.prototype.setCret = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * @enum {number}
 */
proto.GSMgr.TableStatus = {
  INIT: 0,
  PLAY: 1,
  OVER: 2,
  CANCELED: 3
};

goog.object.extend(exports, proto.GSMgr);
